recipe: default.v1
assistant_id: mybot_default
language: zh
pipeline:
- name: "SpacyNLP"
  model: "zh_core_web_lg"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
  use_word_boundaries: False
- name: RegexEntityExtractor
  case_sensitive: false
  use_lookup_tables: true
  use_word_boundaries: False
  use_regexes: True
- name: EntitySynonymMapper
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
    - number
- name: "SpacyEntityExtractor"
- name: "DIETClassifier"
  epochs: 100
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
  - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
